/*
  Warnings:

  - The values [VIEW_PRODUCT,ADD_TO_CART,REMOVE_FROM_CART,UPDATE_CART,START_CHECKOUT,CANCEL_PURCHASE] on the enum `ActionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ActionType_new" AS ENUM ('PRODUCT_VIEW', 'PRODUCT_SEARCH', 'PRODUCT_FILTER', 'PRODUCT_SORT', 'CART_ADD', 'CART_REMOVE', 'CART_UPDATE', 'CART_SAVE_FOR_LATER', 'CHECKOUT_START', 'COMPLETE_PURCHASE', 'PAYMENT_ERROR', 'ADDRESS_UPDATE', 'PRODUCT_BUY_AGAIN', 'PURCHASE_CANCEL', 'PRODUCT_REVIEW', 'RETURN_REQUESTED', 'RETURN_COMPLETED', 'RETURN_CANCELLED', 'PURCHASE_DELIVERY_STATUS_VIEW', 'USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER_START', 'USER_REGISTER_COMPLETE', 'PROFILE_UPDATE', 'PASSWORD_CHANGE', 'DELETE_ACCOUNT');
ALTER TABLE "UserActionLog" ALTER COLUMN "actionType" TYPE "ActionType_new" USING ("actionType"::text::"ActionType_new");
ALTER TYPE "ActionType" RENAME TO "ActionType_old";
ALTER TYPE "ActionType_new" RENAME TO "ActionType";
DROP TYPE "ActionType_old";
COMMIT;
