import type { Metadata } from "next";
import Link from 'next/link';
import "../../globals.css";
import Sidebar from '@/components/layout/Sidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <div className="flex">
          <Sidebar />
          <main className="flex-1 container mx-auto px-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
