### ==================== 環境設定 ====================
@ecsHost = 35.77.48.143
@localHost = localhost
@port = 8000

http://35.77.48.143:3000

### Base URLs
@localBaseUrl = http://{{localHost}}:{{port}}


### /
GET {{localBaseUrl}}/
