### ==================== 環境設定 ====================
@ecsHost = 35.77.48.143
@localHost = localhost
@port = 3001

http://35.77.48.143:3000

### Base URLs
@ecsBaseUrl = http://{{ecsHost}}:{{port}}
@localBaseUrl = http://{{localHost}}:{{port}}

### ==================== Fargate環境 ====================
### 情報ログ
GET {{ecsBaseUrl}}/api/log/info

### エラーログ
GET {{ecsBaseUrl}}/api/log/error

### CPU負荷テスト
GET {{ecsBaseUrl}}/api/metrics/cpu-test

### メモリ負荷テスト
GET {{ecsBaseUrl}}/api/metrics/memory-test

### ==================== Local環境 ====================
### 情報ログ
GET {{localBaseUrl}}/api/log/info

### エラーログ
GET {{localBaseUrl}}/api/log/error

### CPU負荷テスト
GET {{localBaseUrl}}/api/metrics/cpu-test

### メモリ負荷テスト
GET {{localBaseUrl}}/api/metrics/memory-test



    # await fetch("http://localhost:3001/api/user", {
    #   method: "POST",
    #   headers: {
    #     'Content-Type': 'application/json',
    #   },
    #   body: JSON.stringify({ email: email, sub: sub }),
    # });
### メーザー登録

POST {{localBaseUrl}}/api/user
Content-Type: application/json

{
  "email": "test03@example.com",
  "sub": "17441a88-60f1-709b-b7e3-3e3173aca5d62"
}